version: '3.4'

services:
  tilework:
    image: tilework
    build:
      context: .
      dockerfile: tilework/Dockerfile
    ports:
      - 5180:5180
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
